services:
  # # Next.js frontend application
  feeder:
    container_name: cat-feeder
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    # - "3000:3000"
    networks:
      - proxy
    environment:
      - NEXT_PUBLIC_MQTT_HOST=http://mqtt.gatitos.cloud
    volumes:
      - next_logs:/app/logs
    depends_on:
      - mosquitto
    restart: unless-stopped

  # Mosquitto MQTT broker with WebSocket support
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    networks:
      - proxy
    # ports:
    #   - "1883:1883" # MQTT port (for ESP8266)
    #   - "9001:9001" # WebSocket port (for Next.js)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log
    restart: unless-stopped

volumes:
  mosq_data:
  mosq_log:
  next_logs:
networks:
  proxy:
    external: true
