services:
  # # Next.js frontend application
  nextjs:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    # ports:
    #   - "3000:3000"
    # networks:
    #   - proxy
    environment:
      - NEXT_PUBLIC_MQTT_HOST=ws://mosquitto:9001
    depends_on:
      - mosquitto
    restart: unless-stopped

  # Mosquitto MQTT broker with WebSocket support
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    # networks:
    #   - proxy
    # ports:
    #   - "1883:1883" # MQTT port (for ESP8266)
    #   - "9001:9001" # WebSocket port (for Next.js)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

networks:
  proxy:
    external: true
